# Site settings
title: "Weathered"
description: "Outdoor adventures, gear reviews, and trip reports"
url: "https://shanehaynes.github.io/OutoorBlog"
baseurl: "/OutoorBlog"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year-:month-:day-:title/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _posts
  - _layouts
  - _includes
  - assets
